# -*- coding: utf-8 -*-
"""IDS_Assignment-1 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15cyjaZX8SqgNCgoTsipBQFF8rpcMfyVQ

## <center>        **Introduction to Data Science (S2-22_DSECLZG532)-ASSIGNMENT**</center>

## Group No

## Group Member Names:
1.
2.
3.
4.

# 1. Business Understanding

Students are expected to identify an analytical problem of your choice. You have to detail the Business Understanding part of your problem under this heading which basically addresses the following questions.

   1. What is the business problem that you are trying to solve?
   2. What data do you need to answer the above problem?
   3. What are the different sources of data?
   4. What kind of analytics task are you performing?

Score: 1 Mark in total (0.25 mark each)

--------------Type the answers below this line--------------

1. The business problem is the detection of fraudulent transactions within bank transactions. Fraudulent transactions are those transactions made without the authorization of the account holder, which can lead to significant financial losses for both customers and financial institutions.

In the banking industry, fraudulent transactions represent a significant risk, both in terms of financial damage and reputational harm. The challenge for banks is to detect these fraudulent transactions in real-time, minimizing losses while ensuring that legitimate transactions are not unnecessarily blocked or flagged.

Here, the goal is to develop a machine learning model or analytical framework that can accurately detect fraud in transactions.

2. To solve this fraud detection problem, several types of data are required:
Customer details, transaction details, fraud labels, device and location information.

3. The data required for this fraud detection problem typically comes from various sources within the banking system, including: Internal transaction logs, customer information systems, fraud detection systems, third-party data sources, mobile/web app logs, transaction history.

4. This is a supervised binary classification problem, with potential elements of anomaly detection and real-time analytics to predict and identify fraudulent transactions. The model will be trained on historical transaction data where the target variable (Is_Fraud) is labeled as either 0 (not fraud) or 1 (fraud). This makes it a supervised machine learning task.

# 2. Data Acquisition

For the problem identified , find an appropriate data set (Your data set must
be unique with minimum **20 features and 10k rows**) from any public data source.

---



## 2.1 Download the data directly
"""

##---------Type the code below this line------------------##
!pip install opendatasets

import opendatasets as od

od.download("https://www.kaggle.com/datasets/marusagar/bank-transaction-fraud-detection")

#{"username":"swarali01234","key":"3f020ae542014e3aaa65015f95fc62c8"}

import os

data_dir = r'./bank-transaction-fraud-detection'

os.listdir(data_dir)

"""## 2.2 Code for converting the above downloaded data into a dataframe"""

##---------Type the code below this line------------------##

import pandas as pd
import os

# Get the current working directory
current_directory = os.getcwd()

# Construct the path to the CSV file
file_path = os.path.join(current_directory, 'bank-transaction-fraud-detection', 'Bank_Transaction_Fraud_Detection.csv')

# Read the CSV file using the full path
fraud_df = pd.read_csv(file_path)

fraud_df

"""## 2.3 Confirm the data has been correctly by displaying the first 5 and last 5 records."""

##---------Type the code below this line------------------##

# Print the first 5 rows of the dataset
fraud_df.head()

# Print the last 5 rows of the dataset
fraud_df.tail()

"""## 2.4 Display the column headings, statistical information, description and statistical summary of the data."""

##---------Type the code below this line------------------##

# 1. Display Column Headings (Names)
print("Column Headings:")
print(fraud_df.columns)

# 2. Display General Statistical Information about the DataFrame
print("\nGeneral Information:")
fraud_df.info()

# 3. Display Statistical Summary for Numerical Columns
print("\nStatistical Summary for Numerical Columns:")
print(fraud_df.describe())

# 4. Display Description for Non-Numeric Columns (Categorical Data)
print("\nDescription of Non-Numeric Columns:")
print(fraud_df.describe(include=['object']))  # 'object' refers to non-numeric data types like strings

# 5. Display Statistical Summary for Both Numeric and Non-Numeric Data
print("\nStatistical Summary for All Columns:")
print(fraud_df.describe(include='all'))  # Include all types of data (numeric and non-numeric)

"""## 2.5 Write your observations from the above.
1. Size of the dataset
2. What type of data attributes are there?
3. Is there any null data that has to be cleaned?

Score: 2 Marks in total (0.25 marks for 2.1, 0.25 marks for 2.2, 0.5 marks for 2.3, 0.25 marks for 2.4, 0.75 marks for 2.5)

--------------Type the answers below this line--------------

1. Size of the Dataset:
The total size of the dataset is very large. The dataset has 200000 rows (data entries) and 24 columns (attributes/features).

2.  We can categorize the data attributes into two types: Numerical and Categorical. Summary of Data Attribute Types is as follows:

Categorical (Object/Strings):
Customer_Name, Gender, State, City, Bank_Branch, Account_Type, Transaction_Type, Merchant_ID, Merchant_Category, Transaction_Device, Transaction_Location, Device_Type, Transaction_Currency, Customer_Contact, Transaction_Description, Customer_Email.

Numerical (Integer/Float):Age, Transaction_Amount, Account_Balance, Is_Fraud.

Date/Time:Transaction_Date, Transaction_Time

Is_Fraud: This is a binary classification column (0 or 1), it is still considered numerical since it contains numeric values, but it represents a categorical concept (fraud vs. not fraud).

3. Null Data (Missing Values):
There are no null values in the dataset, as indicated by the .info() method.
No data cleaning is required for missing values.

# 3. Data Preparation

If input data is numerical or categorical, do 3.1, 3.2 and 3.4
If input data is text, do 3.3 and 3.4

## 3.1 Check for

* duplicate data
* missing data
* data inconsistencies
"""

##---------Type the code below this line------------------##

# Check for duplicate rows
duplicates = fraud_df.duplicated()  # Returns a boolean Series (True if the row is a duplicate)
print(f"Number of duplicate rows: {duplicates.sum()}")

# Check for missing values in the entire dataset
missing_data = fraud_df.isnull().sum()
print("Missing Data per column:")
print(missing_data)

# Check for columns with missing data
print("\nColumns with missing data:")
print(missing_data[missing_data > 0])

# Check percentage of missing data for each column
missing_percentage = (missing_data / len(fraud_df)) * 100
print("\nPercentage of Missing Data per column:")
print(missing_percentage)

# Optionally, drop rows or columns with missing data if required
df = fraud_df.dropna()  # Drop rows with any missing values
df1 = fraud_df.dropna(axis=1)  # Drop columns with any missing values

# Check for negative or unrealistic values in numerical columns
numerical_columns = fraud_df.select_dtypes(include=['float64', 'int64']).columns
for column in numerical_columns:
    print(f"\n{column} - Values less than 0:")
    print(df[fraud_df[column] < 0])  # Check for negative values (if inappropriate for that column)

# Check for inconsistent categories in categorical columns
categorical_columns = fraud_df.select_dtypes(include=['object']).columns
for column in categorical_columns:
    print(f"\n{column} - Unique categories:")
    print(df[column].unique())  # List all unique values in the column

# Check for possible inconsistencies like case sensitivity
    print(f"\n{column} - Case insensitive categories:")
    print(df[column].str.lower().unique())  # Check if there are case differences

"""## 3.2 Apply techiniques
* to remove duplicate data
* to impute or remove missing data
* to remove data inconsistencies

"""

##---------Type the code below this line------------------##

# 1. Remove Duplicate Data
df = fraud_df.drop_duplicates()

# Display duplicate rows if any
print(fraud_df[duplicates])  # Shows rows that are duplicates

# 2. Impute or Remove Missing Data
# For numerical columns, fill missing values with the mean
numerical_columns = fraud_df.select_dtypes(include=['float64', 'int64']).columns
for column in numerical_columns:
    df[column] = df[column].fillna(df[column].mean())

# For categorical columns, fill missing values with the mode
categorical_columns = fraud_df.select_dtypes(include=['object']).columns
for column in categorical_columns:
    df[column] = df[column].fillna(df[column].mode()[0])

# 3. Remove Data Inconsistencies
# Remove rows with negative values in numerical columns
for column in numerical_columns:
    df = df[df[column] >= 0]  # Remove rows with negative values

# Standardize categorical values
for column in categorical_columns:
    df[column] = df[column].str.lower()  # Convert to lowercase
    df[column] = df[column].str.capitalize()  # Capitalize first letter

# Check the cleaned data
print("Data after cleaning:")
print(fraud_df.head())

# Check for any missing values after cleaning
print("\nMissing values after cleaning:")
print(fraud_df.isnull().sum())

"""## 3.3 Encode categorical data"""

##---------Type the code below this line------------------##

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

# Apply Label Encoding or One-Hot Encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

print("Categorical columns encoded:", categorical_cols.tolist())

"""## 3.4 Report

Mention and justify the method adopted
* to remove duplicate data, if present
* to impute or remove missing data, if present
* to remove data inconsistencies, if present

OR for textdata
* How many tokens after step 3?
* how may tokens after stop words filtering?

If the any of the above are not present, then also add in the report below.

Score: 2 Marks (based on the dataset you have, the data prepreation you had to do and report typed, marks will be distributed between 3.1, 3.2, 3.3 and 3.4)
"""

##---------Type the code below this line------------------##

# Check for duplicate data
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# Remove duplicate rows if present
if duplicates > 0:
    df = df.drop_duplicates()
    print(f"Duplicate rows removed. Remaining rows: {df.shape[0]}")
else:
    print("No duplicate rows found.")

# Check for missing values
missing_values = df.isnull().sum()
print("Missing values in each column:")
print(missing_values[missing_values > 0])

# Impute or remove missing data
if missing_values.any():
    df = df.fillna(df.mean())  # Impute numerical columns with the mean
    print("Missing values imputed with column mean.")
else:
    print("No missing values found.")

# Check for data inconsistencies
# Example: Handling negative or out-of-range values for numerical columns
for col in df.select_dtypes(include=['number']).columns:
    if (df[col] < 0).any():
        print(f"Inconsistent data found in column '{col}'. Replacing negative values with 0.")
        df[col] = df[col].apply(lambda x: max(x, 0))
print("Data inconsistencies addressed if present.")

# Text data processing (if applicable)
text_columns = df.select_dtypes(include=['object']).columns
for col in text_columns:
    df[col] = df[col].astype(str)  # Ensure text data is in string format

# Tokenization and stop words filtering (example for text data)
from sklearn.feature_extraction.text import CountVectorizer

if len(text_columns) > 0:
    text_col = text_columns[0]  # Example: Using the first text column
    vectorizer = CountVectorizer(stop_words='english')
    tokens = vectorizer.fit_transform(df[text_col])

    print(f"Number of tokens after step 3: {tokens.shape[1]}")
    print("Number of tokens after stop words filtering:", len(vectorizer.get_feature_names_out()))
else:
    print("No text data present for tokenization.")

# Justification:
# - Duplicate data is removed to prevent redundancy and ensure data integrity.
# - Missing data is imputed with the mean (for numerical data) to retain as much data as possible.
# - Data inconsistencies, like negative values where not applicable, are corrected.
# - For text data, tokenization is performed, and stop words are filtered to improve model performance.

"""## 3.5 Identify the target variables.

* Separate the data from the target such that the dataset is in the form of (X,y) or (Features, Label)

* Discretize / Encode the target variable or perform one-hot encoding on the target or any other as and if required.

* Report the observations

Score: 1 Mark
"""

##---------Type the code below this line------------------##

# Identify the target column
target_column = 'Is_Fraud'

# Separate the features (X) and target (y)
X = df.drop(columns=[target_column])
y = df[target_column]

# Check if the target variable is categorical
if y.dtype == 'object':
    from sklearn.preprocessing import LabelEncoder
    le = LabelEncoder()
    y = le.fit_transform(y)
    print(f"Target variable '{target_column}' encoded as categorical.")
    print("Classes:", le.classes_)
else:
    print(f"Target variable '{target_column}' is numerical.")

# Report the observations
print("Feature set (X) shape:", X.shape)
print("Target (y) shape:", y.shape)
print("Sample of Features (X):")
print(X.head())
print("Sample of Target (y):")
print(y[:5])

# Observations:
# - The target variable is separated from the features.
# - If categorical, the target is encoded using LabelEncoder.
# - The dataset is now in the form (X, y) suitable for model training.

"""# 4. Data Exploration using various plots

## 4.1 Scatter plot of each quantitative attribute with the target.

Score: 1 Mark
"""

##---------Type the code below this line------------------##

import matplotlib.pyplot as plt
import seaborn as sns

# Identify quantitative (numerical) attributes
quantitative_cols = X.select_dtypes(include=['number']).columns
print("Quantitative Attributes:", list(quantitative_cols))

# Plot scatter plots of each quantitative attribute against the target
for col in quantitative_cols:
    plt.figure(figsize=(8, 6))
    plt.scatter(X[col], y, alpha=0.5)
    plt.title(f'Scatter Plot: {col} vs Target')
    plt.xlabel(col)
    plt.ylabel('Target')
    plt.grid(True)
    plt.show()

# Alternatively, using Seaborn for enhanced visualization
for col in quantitative_cols:
    plt.figure(figsize=(8, 6))
    sns.scatterplot(x=X[col], y=y)
    plt.title(f'Scatter Plot: {col} vs Target')
    plt.xlabel(col)
    plt.ylabel('Target')
    plt.grid(True)
    plt.show()

# Observations:
# - These scatter plots help to observe relationships between each quantitative attribute and the target.
# - Patterns or correlations can be identified to guide feature selection or engineering.

"""## 4.2 EDA using visuals
* Use (minimum) 2 plots (pair plot, heat map, correlation plot, regression plot...) to identify the optimal set of attributes that can be used for classification.
* Name them, explain why you think they can be helpful in the task and perform the plot as well. Unless proper justification for the choice of plots given, no credit will be awarded.

Score: 2 Marks
"""

##---------Type the code below this line------------------##

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Sampling Strategy:
# Using Random Sampling to maintain distribution integrity
# Sampling 10000 rows if the dataset is larger than 1000 rows
sample_size = 10000
sampled_df = df.sample(n=sample_size, random_state=42) if len(df) > sample_size else df

# Statistical Justification: Correlation Analysis
# Calculate correlation with target variable
correlation_matrix = df.corr()
target_corr = correlation_matrix[target_column].abs().sort_values(ascending=False)

# Select Top 10 Features with Highest Correlation
top_corr_features = target_corr.head(11).index  # Including the target variable
print("Top Correlated Features with Target Variable:")
print(target_corr.head(11))

# 1. Correlation Heatmap
# Justification:
# - Correlation heatmap helps identify multicollinearity among top features.
# - It visualizes the strength and direction of relationships.

plt.figure(figsize=(10, 8))
sns.heatmap(df[top_corr_features].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of Top Features')
plt.show()

# 2. Pair Plot
# Justification:
# - Pair plot visually shows the distribution and relationship between the top correlated features.
# - It helps identify potential clusters or patterns that are useful for classification.

sns.pairplot(sampled_df[top_corr_features], hue=target_column, palette='viridis')
plt.suptitle('Pair Plot of Top Correlated Features', y=1.02)
plt.show()

# Observations:
# - Random sampling preserves the overall data distribution.
# - Selected attributes show statistically significant correlations with the target variable.
# - These features provide valuable insights for classification tasks.

"""# 5. Data Wrangling

## 5.1 Univariate Filters

#### Numerical and Categorical Data
* Identify top 5 significant features by evaluating each feature independently with respect to the target/other variable by exploring
1. Mutual Information (Information Gain)
2. Gini index
3. Gain Ratio
4. Chi-Squared test
5. Strenth of Association

(From the above 5 you are required to use only any <b>two</b>)



Score: 3 Marks
"""

##---------Type the code below this line------------------##
import pandas as pd
from sklearn.feature_selection import mutual_info_classif, chi2
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from scipy.stats import chi2_contingency


# Separate features and target variable
X = df.drop(columns=[target_column])
y = df[target_column]

# Encode categorical variables
label_encoders = {}
for column in X.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X[column] = le.fit_transform(X[column])
    label_encoders[column] = le

# Standardize numerical variables
scaler = StandardScaler()
X[X.select_dtypes(include=['float64', 'int64']).columns] = scaler.fit_transform(X[X.select_dtypes(include=['float64', 'int64']).columns])

# Ensure non-negative values for Chi-Squared test
min_max_scaler = MinMaxScaler()
X[X.columns] = min_max_scaler.fit_transform(X[X.columns])

# Calculate Mutual Information
mutual_info = mutual_info_classif(X, y)
mutual_info_series = pd.Series(mutual_info, index=X.columns).sort_values(ascending=False)

# Calculate Chi-Squared test
chi2_values, p_values = chi2(X, y)
chi2_series = pd.Series(chi2_values, index=X.columns).sort_values(ascending=False)


# Select Top 5 Features based on each method
top_5_mutual_info_features = mutual_info_series.head(5).index
top_5_chi2_features = chi2_series.head(5).index


print("Top 5 Features based on Mutual Information:")
print(mutual_info_series.head(5))

print("\nTop 5 Features based on Chi-Squared test:")
print(chi2_series.head(5))

"""## 5.2 Report observations

Write your observations from the results of each method. Clearly justify your choice of the method.

Score 1 mark

--------------Type the answers below this line--------------

The Mutual Information values indicate the dependency between each feature and the target variable Is_Fraud. The top features identified are:

Gender: 0.011630
Account_Type: 0.007414
Device_Type: 0.005173
Transaction_Type: 0.004666
Merchant_Category: 0.002393
These values are relatively low, suggesting that while these features do share some information with the target variable, the dependency is not very strong. This means that these features might not be highly predictive of fraud on their own but could still contribute to the overall model when combined with other features.

Chi-Squared Test
The Chi-Squared values indicate the strength of association between each feature and the target variable Is_Fraud. The top features identified are:

State: 1.151094
Transaction_ID: 0.544867
Account_Type: 0.446829
City: 0.270188
Bank_Branch: 0.270188
These values are higher compared to the Mutual Information values, suggesting a stronger association with the target variable. However, the values are still relatively low, indicating that these features may not be highly predictive on their own but could still be useful in combination with other features.

Inferences
From the values, we can infer that:
State,Account_Type, City, Bank_Branch and Gender are overall our top 5 features, but the values are still relatively lower than expected, so there isn't a strong association.

Why did I choose these two options:

I chose Mutual Information and Chi-Squared test methods for evaluating the significance of features with respect to the target variable Is_Fraud because they offer complementary insights into the relationships between features and the target variable.

Complementary Insights
By using both Mutual Information and Chi-Squared test, you gain a comprehensive understanding of feature importance:

Mutual Information captures non-linear dependencies and interactions, providing insights into how much information each feature shares with the target variable.
Chi-Squared Test assesses the strength of association between categorical features and the target variable, highlighting features that are significantly associated with the target variable.
Combining these methods allows you to identify features that are both informative and strongly associated with the target variable, leading to a more robust feature selection process for your predictive model.

# 6. Implement Machine Learning Techniques

Use any 2 ML tasks
1. Classification  

2. Clustering  

3. Association Analysis

4. Anomaly detection

You may use algorithms included in the course, e.g. Decision Tree, K-means etc. or an algorithm you learnt on your own with a brief explanation.
A clear justification have to be given for why a certain algorithm was chosen to address your problem.

Score: 4 Marks (2 marks each for each algorithm)

## 6.1 ML technique 1 + Justification

--------------Type the answers below this line--------------

ML Technique: K-Nearest Neighbors (KNN)

Justification:
K-Nearest Neighbors (KNN) is an intuitive and effective classification algorithm that makes predictions based on the similarity between data points. It is particularly suitable for this problem because:

Versatility with Data Types: KNN can seamlessly handle both numerical and categorical data, which is ideal for attributes such as gender, account type, city, and branch.
Non-parametric Nature: As a non-parametric model, KNN does not assume any underlying distribution, allowing it to adapt to complex decision boundaries.
Localized Decision Making: KNN's decision-making is based on localized patterns, making it effective in detecting fraudulent transactions that might exhibit unique characteristics in certain regions of the feature space.
Simplicity and Interpretability: The algorithm is simple to understand and implement, and its decision-making process is transparent, enhancing model interpretability.
"""

#KNN
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Separate features and target variable
X = df.drop(columns=[target_column])
y = df[target_column]

# Encode categorical variables
label_encoders = {}
for column in X.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X[column] = le.fit_transform(X[column])
    label_encoders[column] = le


# Classification using RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=20)
clf = RandomForestClassifier(random_state=20)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("Classification Report:")
print(classification_report(y_test, y_pred, zero_division=1))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""## 6.2 ML technique 2 + Justification

--------------Type the answers below this line--------------

ML Technique: Decision Tree

Justification:
Decision Trees are highly interpretable and powerful classifiers that provide a clear and logical representation of the decision-making process. This makes them suitable for the current problem due to the following reasons:

Intuitive Visualization: Decision Trees offer an intuitive, hierarchical structure that clearly outlines the decision path, making it easier to explain and justify predictions.
Handling Categorical Data: They naturally handle categorical variables without requiring extensive preprocessing, making them well-suited for features such as gender, account type, city, and branch.
Non-linear Relationships: Decision Trees effectively capture non-linear interactions between variables, enabling the model to learn complex patterns associated with fraudulent transactions.
Feature Importance Insight: By evaluating the importance of each feature, Decision Trees provide valuable insights into the most influential factors driving the predictions, enhancing interpretability and trust in the model.
"""

#DecisionTree

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

target_column = 'Is_Fraud'  # Replace with your actual target column name

# Select top features identified from Mutual Information and Chi-Squared test
# Separate features and target variable
X = df.drop(columns=[target_column])
y = df[target_column]

# Encode categorical variables
label_encoders = {}
for column in X.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X[column] = le.fit_transform(X[column])
    label_encoders[column] = le

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Classification using DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("Classification Report:")
print(classification_report(y_test, y_pred, zero_division=1))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""## 7. Conclusion

Compare the performance of the ML techniques used.

Derive values for preformance study metrics like accuracy, precision, recall, F1 Score, AUC-ROC etc to compare the ML algos and plot them. A proper comparision based on different metrics should be done and not just accuracy alone, only then the comparision becomes authentic. You may use Confusion matrix, classification report, Word cloud etc as per the requirement of your application/problem.

Score 1 Mark

--------------Type the answers below this line--------------

Compare the performance of the ML techniques used.

Accuracy:
KNN : 0.95
Decision Tree : 0.89

Precision

KNN:
Class 0: 0.95
Class 1: 1.00

Decision Tree:
Class 0: 0.95
Class 1: 0.05

Recall

KNN:
Class 0: 1.00
Class 1: 0.00

Decision Tree:
Class 0: 0.94
Class 1: 0.06

F1-Score

KNN:
Class 0: 0.97
Class 1: 0.00

Decision Tree:
Class 0: 0.94
Class 1: 0.05

Confusion Matrix:
KNN:
[[75955     0]
 [ 4045     0]]
Decision Tree:

[[71114  4801]
 [ 3835   250]]


Analysis
KNN: The KNN classifier shows high precision and recall for class 0, but it fails to predict class 1 correctly, resulting in an AUC-ROC of 0.00. This indicates that the model is highly biased towards class 0.

Decision Tree: The Decision Tree classifier has a slightly lower accuracy compared to KNN but provides a more balanced performance across both classes. The AUC-ROC of 0.07 indicates that it has some ability to distinguish between the classes, although it is still quite low.

In conclusion, while the KNN classifier shows higher accuracy, it is not effective in predicting class 1. The Decision Tree classifier, on the other hand, provides a more balanced performance but with lower overall accuracy.

## 8. Solution

What is the solution that is proposed to solve the business problem discussed in Section 1. Also share your learnings while working through solving the problem in terms of challenges, observations, decisions made etc.

Score 2 Marks

--------------Type the answers below this line--------------

The solution proposed is to use a Decision Tree Model to predict the nature of any transaction.
Learnings:
1. We explored different methods to find out the most associated variables to our target. After analysis, we found gini index and gain ratio to be similar to each other and co dependent. So we went with the methods of Mutual Information and Chi sq test.
2. Different ML Models react differently to different datasets. A model with higher accuracy doesn't necessarily mean its better. It could be biased towards a particular solution, like we see it in our case with KNN.

Challanges and Decisions:
1. Finding a real world problem and defining a model to solve the issue is not easy. We went through many datasets before finalising on this one.
2. Trying out different combinations of parameters to choose for our models, through trial and test method we found it best to use all parameters. In cases of choosing certain parameters, accuracy dropped down by 0.02 in some cases.

##NOTE
All Late Submissions will incur a penalty of -2 marks. Do ensure on time submission to avoid penalty.

Good Luck!!!
"""
